### ISSUE TITLE
Install document update

### ISSUE THREAD

**Issue by adrienkortext** [ericoc/zabbix-slack-alertscript#17]
You should add a section to the zabbix configuration stating that a zabbix-server restart is required for the script to get picked up and start working.   It is mentioned in passing in the section where you create the script but I believe you need to do the restart after you configure the script as a media type.

**Comment by ericoc** [comment]
Do you definitely have to restart the zabbix-server process/daemon during the installation of the alert script? Is there any specific version of the Zabbix server that you had a problem with? Any more details you could offer would be nice since the only scenario I know of that requires a restart of the zabbix-server process is updates to the Zabbix server configuration file (like changing `AlertScriptsPath` in `zabbix_server.conf`).

Nothing on the documentation on zabbix.com mentions restarting after making changes to custom alertscripts themselves. I also don't believe that any changes within the web UI require a restart of the zabbix-server daemon.

**Comment by adrienkortext** [comment]
I followed the steps in the guide exactly on zabbix 3.0.4 on Debian,
running on top of VMware.

I tested the script grow the client to be sure it would fire and set up a
media type,  user, action etc.

Triggers that fired would not use the newly configured action until after I
restarted the zabbix-server service.

**Comment by adrienkortext** [comment]
Tested from the CLI*

**Comment by ericoc** [comment]
Hmmm, alright. Did you update `AlertScriptsPath` in your `zabbix_server.conf` configuration file during the installation process?

It makes sense that you would have needed to restart if you updated `AlertScriptsPath`, but otherwise, I can't see a reason for a restart of the daemon being necessary. The web UI changes are all just updates to whatever backend database (MySQL/PostgreSQL/etc.) that you have set up for Zabbix to use.

**Comment by adrienkortext** [comment]
I didn't have to touch it,  I just checked the config to see where to
create the script.

**Comment by ericoc** [comment]
On Zabbix 3.0.7, as a test, I just created a `test.sh` inside of my `AlertScriptsPath` containing only the following:

    #!/bin/bash
    echo "$1 $2 $3" >> /tmp/zabbix-alert-test

I added a Media Type called "Test" (configured identically to the Slack one defined in my README) pointing to that `test.sh` script. I assigned a "Send to" value of "test" for the "Test" media type under my Zabbix user account. I then took down Redis on my server causing an alert to trigger (and eventually brought it back up triggering a recovery); the alert script executed successfully without ever requiring a restart of the `zabbix-server` daemon:

    $ cat /tmp/zabbix-alert-test
    test PROBLEM Redis service is down on ericoc.com - ericoc.com (127.0.0.1)
    test RECOVERY Redis service is down on ericoc.com - ericoc.com (127.0.0.1)

My testing confirms that custom alertscripts can definitely be added and implemented without restarting the `zabbix-server` daemon. I can't explain why it would not have worked for you without a restart of the service, but it could have been that the `slack.sh` script was not executable - or, if you were setting up a new installation, simply a strange side effect of that process.
